### ISSUE TITLE
CRITICAL:degiro_connector.quotecast.tools.ticker_fetcher:A new "session_id" is required.

### ISSUE THREAD

**Issue by nine1zero** [Chavithra/degiro-connector#151]
Hi need some help.

I have been using the API for many years now though a Google Cloud fucntion,  always working perfectly.
Recently updated the code to 3.0.22,  but I couldn't make the quotecast login to work.
The code used is below, almost exactly the same as the examples provided for [realtime_one_shot.py](https://github.com/Chavithra/degiro-connector/blob/main/examples/quotecast/realtime_one_shot.py)
```
        # REAL TIME PRICE
        logging.basicConfig(level=logging.INFO)
        logger = TickerFetcher.build_logger()
        session = TickerFetcher.build_session()
        ticker_to_df = TickerToDF()
        ticker_request = TickerRequest(
            request_type="subscription",
            request_map={
                pdt_vwdId: [
                    "LastDate",
                    "LastTime",
                    "LastPrice",
                    "LastVolume",
                ],
            },
        )

        # FETCH METRICS
        session_id_rt = TickerFetcher.get_session_id(user_token=user_token)
        if session_id_rt is None:
            raise TypeError("`session_id_rt` is None")
        else:
            print("Get real-time session_id_rt:", session_id_rt)

        TickerFetcher.subscribe(
            ticker_request=ticker_request,
            session_id=session_id_rt,
            session=session,
            logger=logger,
        )

        ticker = TickerFetcher.fetch_ticker(
            session_id=session_id_rt,
            session=session,
            logger=logger,
        )

        if ticker is None:
            raise TypeError("`ticker` is None")
```

The error is the one in the subject issue, here the logs (session ID seems ok):

<img width="1149" alt="image" src="https://github.com/user-attachments/assets/e20043b2-7a74-4258-9d49-4232bd5ecb0e">

Any ideas? many thanks

**Comment by richardbeumer** [comment]
Same issue here. Any help would be very welcome.

**Comment by uvrt** [comment]
I have the same issue. However on my development machine (macos) exactly the same code is working while on my production system (linux flavor) not.

**Comment by Chavithra** [comment]
Hello @nine1zero @uvrt ,

do you have a way to reproduce it ?

Feel free to join me on Discord.

Thanks

**Comment by MichielvanBeers** [comment]
Hi,

Did any of you end up resolving this issue? I experience a similar issue where everything works as expected while developing on my Windows machine (using Docker), but when I deploy it to my server, I get the same error as described above.

**Comment by richardbeumer** [comment]
Sorry for the late reply, found a  workaround some time ago, but this doesn't seem to be working as expected.

When running code below on WSL2 (Ubuntu) I get the same error:

Code:
```
logger = TickerFetcher.build_logger()
session = TickerFetcher.build_session()
ticker_to_df = TickerToDF()
user_token = self.connector.get_user_token(self.trading_api)
print("user_token: ", user_token)
print(self.trading_api.get_config())
product=product_id.__str__()
ticker_request = TickerRequest(
    request_type="subscription",
    request_map={
        product: [
            "LastDate",
            "LastTime",
            "LastPrice",
            "LastVolume",
        ],

    },
)

session_id = TickerFetcher.get_session_id(user_token=user_token)
if session_id is None:
    raise TypeError("`session_id` is None")

TickerFetcher.subscribe(
    ticker_request=ticker_request,
    session_id=session_id,
    session=session,
    logger=logger,
)

ticker = TickerFetcher.fetch_ticker(
    session_id=session_id,
    session=session,
    logger=logger,
)

if ticker is None:
    raise TypeError("`ticker` is None")

df = ticker_to_df.parse(ticker=ticker)
print(df)
```

Error:
```
A new "session_id" is required.
A new "session_id" is required.
Traceback (most recent call last):
  File "/home/richard/projects/private/degiro/src/test.py", line 10, in <module>
    print(test.get_current_price_info(xxxxxxx))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/projects/private/degiro/src/buy.py", line 112, in get_current_price_info
    raise TypeError("`ticker` is None")
TypeError: `ticker` is None
```

**Comment by richardbeumer** [comment]
Sadly I see the same error over and over again. So this doesn't seem to work.

@MichielvanBeers I use the `closePrice` of a stock to create a order the next day. This works in 90% of the cases. But if the stock risses on opening the order doesn't get filled. On the other hand there is a risk you will pay a bit more than necessary.
