### ISSUE TITLE
Protobuffer generated code out of date

### ISSUE THREAD

**Issue by marcopus** [Chavithra/degiro-connector#96]
I recently updated the degiro-connector dependency (2.0.21 --> 2.0.22) in my project and I am getting this error when importing the TradingAPI, perhaps some file need to be re-generated?
```
Traceback (most recent call last):
  File "degiro_portfolio_rebalancer.py", line 9, in <module>
    from degiro_connector.trading.api import API as TradingAPI
  File "/home/marcomarra/.cache/pypoetry/virtualenvs/degiro-portfolio-rebalancer-6YkwSdyZ-py3.8/lib/python3.8/site-packages/degiro_connector/trading/api.py", line 15, in <module>
    from degiro_connector.trading.models.trading_pb2 import Credentials
  File "/home/marcomarra/.cache/pypoetry/virtualenvs/degiro-portfolio-rebalancer-6YkwSdyZ-py3.8/lib/python3.8/site-packages/degiro_connector/trading/models/trading_pb2.py", line 37, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/marcomarra/.cache/pypoetry/virtualenvs/degiro-portfolio-rebalancer-6YkwSdyZ-py3.8/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

**Comment by marcopus** [comment]
@Chavithra I pushed the protobuffer code generated for 2.0.22 to a [branch](https://github.com/marcopus/degiro-connector/tree/2.0.22-regenerate-protobuffer-code) in my fork. I could not open a PR against master though, since master is behind 2.0.22 and I am not sure why

**Comment by richardbeumer** [comment]
Hi I'm facing the same issue as above. Is there anyway to get this fixed so we can user the latest version of the dependency?

**Comment by Chavithra** [comment]
Hi, I think it's up to date now
Closing the ticket.
Feel free to open a new one if you still have protobuffer issues.
Thanks
